sudo: required

language: node_js
node_js:
  - "node"

services:
  - docker

script:
  - docker build -f Dockerfile -t "$TRAVIS_REPO_SLUG:$TAG" .
  - docker run "$TRAVIS_REPO_SLUG:$TAG" npm test

after_success:
  - sh deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh deploy_heroku.sh
